web:
  image: nginx:latest
  ports:
    - "8888:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes:
    - ./code:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal